CREATE TABLE IF NOT EXISTS entries (
  id INTEGER PRIMARY KEY,
  day TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL DEFAULT '',
  body_md TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
